#!/bin/sh

. ./settings.sh

oc new-app -e POSTGRESQL_USER=${EVENTS_DATABASE_USERNAME} -ePOSTGRESQL_PASSWORD=${EVENTS_DATABASE_PASSWORD} -ePOSTGRESQL_DATABASE=${EVENTS_DATABASE_NAME} centos/postgresql-10-centos7 --name=${EVENTS_DATABASE_SERVICE_NAME}

oc new-app ${QUARKUS_BUILDER_IMAGE}~${GIT_REPO_URL} \
  -e DB_SERVICE_NAME=${EVENTS_DATABASE_SERVICE_NAME} \
  -e DB_SERVICE_PORT=${EVENTS_DATABASE_SERVICE_PORT} \
  -e DB_NAME=${EVENTS_DATABASE_NAME} \
  -e DB_USERNAME=${EVENTS_DATABASE_USERNAME} \
  -e DB_PASSWORD=${EVENTS_DATABASE_PASSWORD} \
  --context-dir=${EVENTS_CONTEXT_DIR} --name=${EVENTS_SERVICE_NAME}
oc expose svc/${EVENTS_SERVICE_NAME}

oc new-app ${QUARKUS_BUILDER_IMAGE}~${GIT_REPO_URL} \
  --context-dir=${GATEWAY_CONTEXT_DIR} --name=${GATEWAY_SERVICE_NAME}
oc expose svc/${GATEWAY_SERVICE_NAME}

oc new-app ${NODEJS_BUILDER_IMAGE}~${GIT_REPO_URL} \
  --context-dir=${FRONTEND_CONTEXT_DIR} --name=${FRONTEND_SERVICE_NAME}
oc expose svc/${FRONTEND_SERVICE_NAME}


