apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gramola-events-pipeline-complex
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        // Don't forget to run the commands to create the dev project, and grant the needed roles to the service accounts
                
        def BUILD_NAME = COMPONENT_NAME
            
        //def mvnCmd = "mvn -s ./nexus_openshift_settings.xml"
        def mvnCmd = "./mvnw"

        pipeline {
          agent {
            label 'maven'
          }
          stages {
            stage('Checkout') {
              steps {
                git url: "${GIT_URL}", branch: "${GIT_REF}"
              }
            }
            
            stage('Build') {
                steps {
                    dir("${CONTEXT_DIR}") {
                        sh "${mvnCmd} -v"
                        sh "${mvnCmd} clean package -DskipTests -Dquarkus.profile=test"
                    }
                }
            }
            
            stage('Test') {
                steps {
                    dir("${CONTEXT_DIR}") {
                        print "${mvnCmd} test"
                    }
                }
            }
            
            stage('Sonar') {
                steps {
                    script {
                        dir("${CONTEXT_DIR}") {
                          print "${mvnCmd} sonar:sonar -Dsonar.host.url=${SONAR} -Dsonar.projectName=${JOB_BASE_NAME} -Dsonar.login=${SONAR_TOKEN}"
                        }
                    }
                }
            }
            
            stage('Nexus') {
                steps {
                    script {
                      dir("${CONTEXT_DIR}") {
                        print "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::${NEXUS}/repository/maven-snapshots/"
                      }
                    }
                }
            }
                                
            stage('Create Image Builder') {
              when {
                expression {
                  openshift.withCluster() {
                    return !openshift.selector("bc", "${BUILD_NAME}").exists();
                  }
                }
              }
              steps {
                script {
                  openshift.withCluster() {
                    openshift.newBuild("--name=${BUILD_NAME}", "--image-stream=${BUILD_IMAGE_STREAM}", "--binary")
                  }
                }
              }
            }

            stage('Build Image') {
              steps {
                script {
                  dir("${CONTEXT_DIR}") {
                    openshift.withCluster() {
                        openshift.selector("bc", "${BUILD_NAME}").startBuild("--from-file=./target/${COMPONENT_NAME}-${APP_VERSION}-runner.jar", "--wait")
                    }      
                  }
                }
              }
            }

            stage('Create DEV') {
              when {
                expression {
                  openshift.withCluster() {
                      openshift.withProject("${DEV_PROJECT_NAME}") {
                        return !openshift.selector('dc', "${COMPONENT_NAME}").exists()
                      }
                  }
                }
              }
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject("${DEV_PROJECT_NAME}") {
                        openshift.newApp("${DEV_PROJECT_NAME}/${BUILD_NAME}:latest", "--name=${COMPONENT_NAME} -e DB_SERVICE_NAME=${DB_SERVICE_NAME} -e DB_SERVICE_PORT=${DB_SERVICE_PORT} -e DB_NAME=${DB_NAME} -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD}").narrow('svc').expose()
                        //def liveness = openshift.raw( "set probe dc/${COMPONENT_NAME} --liveness --get-url=http://:8080/health/live --initial-delay-seconds=50" )
                        //echo "After set probe liveness: ${liveness.out}"
                        //def readiness = openshift.raw( "set probe dc/${COMPONENT_NAME} --readiness --get-url=http://:8080/api/events --initial-delay-seconds=60" )
                        //echo "After set probe readiness: ${readiness.out}"
                        def partOfLabel = openshift.raw( "label dc/${COMPONENT_NAME} app.kubernetes.io/part-of=${APP_NAME}-app app.kubernetes.io/part-of=gramola-app app.openshift.io/runtime=java" )
                        echo "After label part-of partOfLabel: ${partOfLabel.out}"
                        def annotate = openshift.raw( "annotate dc/${COMPONENT_NAME} app.openshift.io/connects-to='events-database,postgresql-persistent' --overwrite" )
                        echo "After annotate: ${annotate.out}"
                    }
                  }
                }
              }
            }

            stage('Approve') {
                steps {
                    timeout(time:15, unit:'MINUTES') {
                        input message:'Approve Deploy to TEST?'
                    }
                }
            }

            stage('Promote to TEST') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.tag("${BUILD_NAME}:latest", "${BUILD_NAME}:test")
                  }
                }
              }
            }

            stage('Create TEST') {
              when {
                expression {
                  openshift.withCluster() {
                      openshift.withProject("${TEST_PROJECT_NAME}") {
                        return !openshift.selector('dc', "${COMPONENT_NAME}").exists()
                      }
                  }
                }
              }
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject("${TEST_PROJECT_NAME}") {
                        openshift.newApp("${DEV_PROJECT_NAME}/${BUILD_NAME}:test", "--name=${COMPONENT_NAME} -e DB_SERVICE_NAME=${DB_SERVICE_NAME} -e DB_SERVICE_PORT=${DB_SERVICE_PORT} -e DB_NAME=${DB_NAME} -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD}").narrow('svc').expose()
                        //def liveness = openshift.raw( "set probe dc/${COMPONENT_NAME} --liveness --get-url=http://:8080/health/live --initial-delay-seconds=50" )
                        //echo "After set probe liveness: ${liveness.out}"
                        //def readiness = openshift.raw( "set probe dc/${COMPONENT_NAME} --readiness --get-url=http://:8080/api/events --initial-delay-seconds=60" )
                        //echo "After set probe readiness: ${readiness.out}"
                        def partOfLabel = openshift.raw( "label dc/${COMPONENT_NAME} app.kubernetes.io/part-of=${APP_NAME}-app app.kubernetes.io/part-of=gramola-app app.openshift.io/runtime=java" )
                        echo "After label part-of partOfLabel: ${partOfLabel.out}"
                        def annotate = openshift.raw( "annotate dc/${COMPONENT_NAME} app.openshift.io/connects-to='events-database,postgresql-persistent' --overwrite" )
                        echo "After annotate: ${annotate.out}"
                    }
                  }
                }
              }
            }
          }
        }
      env:
        - name: MAVEN_OPTS
          value: >-
            -Dsun.zip.disableMemoryMapping=true -Xms20m
            -Djava.security.egd=file:/dev/./urandom
            -XX:+UnlockExperimentalVMOptions
            -Dsun.zip.disableMemoryMapping=true'
        - name: LAB_INFRA_PROJECT_NAME
          value: "lab-infra"
        - name: APP_NAME
          value: "gramola"
        - name: COMPONENT_NAME
          value: "events"
        - name: APP_VERSION
          value: "1.0.0-SNAPSHOT"
        - name: DEV_PROJECT_NAME
          value: "gramola-dev"
        - name: TEST_PROJECT_NAME
          value: "gramola-test"
        - name: GIT_URL
          value: "https://github.com/cvicens/gramola.git"
        - name: GIT_REF
          value: "master"
        - name: CONTEXT_DIR
          value: "events"
        - name: BUILD_IMAGE_STREAM
          value: "openshift/redhat-openjdk18-openshift:1.5"
        - name: NEXUS
          value: "http://nexus-lab-infra"
        - name: NEXUS_USERNAME
          value: "admin"
        - name: NEXUS_PASSWORD
          value: "admin123"
        - name: NEXUS_PATH
          value: "com/redhat/gramola/events"
        - name: SONAR_TOKEN
          value: "CHANGE_IT"
        - name: SONAR
          value: "http://sonarqube-lab-infra"
        - name: JOB_BASE_NAME
          value: "gramola-events-job"
        - name: DB_USERNAME
          value: "events"
        - name: DB_PASSWORD
          value: "secret"
        - name: DB_SERVICE_NAME
          value: "events-database"
        - name: DB_SERVICE_PORT
          value: "5432"
        - name: DB_NAME
          value: "events"
          
    type: JenkinsPipeline